name: Actualizar Noticias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Librerias
        run: pip install feedparser requests beautifulsoup4

      - name: Ejecutar Bot
        run: python cuervo_bot.py

      - name: Publicar Cambios Forzados
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Actualizacion Crítica InfoGarcia24" || echo "No hay cambios para subir"
          git push origin main
